### ISSUE TITLE
Opción Inválida

### ISSUE THREAD

**Issue by germanp24** [kevin15sandoval/metodologia-de-la-programacion-#1]
Controlar mejor el error producido cuando se introduce una opción inválida

**Comment by chunche95** [comment]
@gmnpjpn  El control de excepciones está creándose en las zona de presentación.
Excepciones controladas:
- Números negativos y strings
- Paso del limite máximo de la superficie (Baldosa más grande que la superficie)
- Control sobre la sobreescritura de las posiciones de las baldosas
- Control sobre los casos con solución imposible.

**Comment by chunche95** [comment]
@gmnpjpn, @kevin15sandoval y @AndresDiazCarrillo mañana vemos los avances que tenemos cada uno.
Sino, hacemos una brainstorming para solucionar esta semana este Hito, porque la semana que viene empezamos con el siguiente, por no decir que será esta.

**Comment by chunche95** [comment]
Para ver las excepciones controladas en el hito 2 - Practica 4 es necesario que vayais a la zona indicada como Exceptions en Main
